# Selected Indian cattle and buffalo breeds with short descriptions

BREEDS = [
    # Cattle
    "Gir",
    "Sahiwal",
    "Red Sindhi",
    "Tharparkar",
    "Kankrej",
    "Rathi",
    "Hariana",
    "Deoni",
    "Ongole (Nellore)",
    "Kangayam",
    "Hallikar",
    "Amrit Mahal",
    "Khillari",
    "Krishna Valley",
    "Malnad Gidda",
    "Vechur",
    "Gaolao",
    "Dangi",
    "Nimari",
    "Siri",
    "Punganur",
    # Buffalo
    "Murrah",
    "Jaffarabadi",
    "Mehsana",
    "Surti",
    "Nili-Ravi",
    "Bhadawari",
    "Nagpuri",
    "Pandharpuri",
    "Toda",
    "Banni",
]

BREED_DESCRIPTIONS = {
    # Cattle
    "Gir": "High milk-yielding Zebu cattle from Gujarat; distinctive convex forehead and long ears.",
    "Sahiwal": "Renowned dairy cattle from Punjab region; heat-tolerant with reddish-brown coat.",
    "Red Sindhi": "Dairy breed from Sindh; deep reddish coat, known for good milk fat percentage.",
    "Tharparkar": "Dual-purpose breed from Thar Desert; white to light grey, hardy and disease-resistant.",
    "Kankrej": "Strong draught and dairy breed from Gujarat/Rajasthan; lyre-shaped horns.",
    "Rathi": "Dual-purpose breed from Rajasthan; good milking ability and adaptability to arid zones.",
    "Hariana": "Draught and dairy breed from Haryana; usually white to grey with sturdy build.",
    "Deoni": "Dual-purpose breed from Deoni region; three color variants and good milk production.",
    "Ongole (Nellore)": "Large Zebu breed from Andhra Pradesh; prized for draught and beef, white-grey coat.",
    "Kangayam": "Draught breed from Tamil Nadu; compact and strong, grey coat with darker forequarters.",
    "Hallikar": "Mysore type draught breed from Karnataka; known for endurance and agility.",
    "Amrit Mahal": "Ancient draught breed from Karnataka; lean body and high stamina.",
    "Khillari": "Draught breed from Maharashtra; long horns and compact body.",
    "Krishna Valley": "Draught breed from Karnataka; large frame, grey coat.",
    "Malnad Gidda": "Small native cattle from Western Ghats; highly disease-resistant and frugal feeder.",
    "Vechur": "One of the smallest cattle breeds from Kerala; efficient and heat-tolerant.",
    "Gaolao": "Draught breed from Maharashtra; light coat, strong with good endurance.",
    "Dangi": "Western Ghats breed; adapted to heavy rainfall and rugged terrain.",
    "Nimari": "Central Indian breed; reddish coat with white patches, multipurpose.",
    "Siri": "Hilly region breed from North-East; small frame adapted to cold.",
    "Punganur": "Dwarf cattle from Andhra Pradesh; small size, hardy and efficient.",

    # Buffalo
    "Murrah": "Premier dairy buffalo from Haryana/Punjab; jet black coat, tightly curled horns.",
    "Jaffarabadi": "Heavy buffalo from Gujarat; massive head and strong build, good milk yield.",
    "Mehsana": "Dairy buffalo from Gujarat; cross of Murrah and Surti, good performance.",
    "Surti": "Buffalo from Gujarat; sickle-shaped horns, moderate milk yield with high fat.",
    "Nili-Ravi": "High-yielding buffalo from Punjab region; wedge-shaped body, excellent dairying.",
    "Bhadawari": "Buffalo from Uttar Pradesh; copper-colored hair, high milk fat percentage.",
    "Nagpuri": "Dual-purpose buffalo from Maharashtra; long sword-shaped horns.",
    "Pandharpuri": "Buffalo from Maharashtra; very long corkscrew horns, good adaptability.",
    "Toda": "Nilgiri hills buffalo; semi-wild with distinct white chevrons.",
    "Banni": "Buffalo from Kutch; hardy desert-adapted breed with good milk production.",
}
